// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMa9QdZdpQNqcMprhAXLIK_GJbD4Fu71o',
    appId: '1:1030927669521:web:aa081bf4ea51505e7154b0',
    messagingSenderId: '1030927669521',
    projectId: 'voice-app-sample',
    authDomain: 'voice-app-sample.firebaseapp.com',
    storageBucket: 'voice-app-sample.appspot.com',
    measurementId: 'G-75EVRVJ4WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbajdR8DTJNClJKPQDooCjCf4NszPGSQ',
    appId: '1:1030927669521:android:b661376b510d854a7154b0',
    messagingSenderId: '1030927669521',
    projectId: 'voice-app-sample',
    storageBucket: 'voice-app-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC079uir1m8ChXKnb3na0BHRYGAzvKupnk',
    appId: '1:1030927669521:ios:aa6bb0778249b08e7154b0',
    messagingSenderId: '1030927669521',
    projectId: 'voice-app-sample',
    storageBucket: 'voice-app-sample.appspot.com',
    androidClientId: '1030927669521-h0rpd7h1lrkhbl78jnmg4obt8j5r8co4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC079uir1m8ChXKnb3na0BHRYGAzvKupnk',
    appId: '1:1030927669521:ios:184cc4dc2683c00d7154b0',
    messagingSenderId: '1030927669521',
    projectId: 'voice-app-sample',
    storageBucket: 'voice-app-sample.appspot.com',
    androidClientId: '1030927669521-h0rpd7h1lrkhbl78jnmg4obt8j5r8co4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
