name: exotel_plugin
description: "A new Flutter plugin project."
version: 1.0.10
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.exotel.voice_plugin
        pluginClass: ExotelPlugin
      ios:
        pluginClass: ExotelPlugin
